### ISSUE TITLE
Suggestion for jammers

### ISSUE THREAD

**Issue by FlyingTaurus523** [GingerWalnut/SQBeyondPublic#108]
I would like to suggest that perhaps when a jammer is activated, It affects slipspace in a 10k radius instead of a 1k radius, but keep the realspace radius of 1k the same.

**Comment by MrBarramundi** [comment]
The Jammer should only work in slip space as far as it does in non-slip space if not less because of maybe some weird slip space rule (Up to dev creative discretion). If a Jammer is to affect a larger radius (especially in slip space) it should have to be a bigger Jammer or a normal Jammer that has to be fed (either by clicking on it or some hopper setup) some sort of resource like gold ingots, emeralds, etc. I myself don't want to be a pirate but I am all for people being pirates but I'm also all for people who just want to play space Minecraft and build and collect resources but there needs to be a balance between offensive and defensive capabilities. The balance can come from Jammers costing resources as previously mentioned especially because more than a few emeralds or gold ingots is at stake for the person being hunted. Hours of work on building a ship or collecting resources could be lost because they couldn't slip because of someone 9,000 blocks way. It would encourages people to just stay on their planets and not fly in and explore space, which hurts the pirates because everyone knows that if a known pirate is in space they could easily disable their escape options from 9,000 blocks away. Long story short, if someone wants to be a pirate then you should have to work for "their food."

**Comment by Jarkyc** [comment]
Denied

**Comment by APnaptime** [comment]
why?
