### ISSUE TITLE
(Suggestion) 2 Helpful ship ideas

### ISSUE THREAD

**Issue by HTCaveman** [GingerWalnut/SQBeyondPublic#442]
It gets annoying when you build a ship, only to find out you are under/over the min/max limit. I think a block counter would help nicely with ships. It could be like "This ship requires atleast 201-500 blocks. It currently has 193 blocks." or, another example, "This ship requires 201-500 blocks. It currently has 543 blocks"

Another idea is add what rep amount it takes to recieve a ship in a faction.
"Cutter
all the info like module limit and speed here
10,000 reputation"
It'd be in the ship class selection or ship class viewer via /ship class. It'd just be under all the information. It'd be useful for people to know what level to grind towards.

**Comment by GingerWalnut** [comment]
We can't easily do more because it could theoretically be detecting the entire world and then it would take a very long time to return the number. Thus, it stops detecting blocks as soon as it goes over the maximum. However, ships being too small is easy and I've added that in for the next restart.

The problem with the ship class reputation (or rank) requirements being listed is that the two are stored in separate plugins. However, I might add it in at some point, it just won't be simple.

**Comment by HTCaveman** [comment]
Yeah but if you do the second one, wouldnt all you have to add is like 1 line of text saying "10,000 reputation"? I don't think it'd have to work with another plugin, it'd just be like a warning

**Comment by GingerWalnut** [comment]
It's harder to add something different for each ship class when it doesnt draw on something to get the data from. We could do it manually, but then it doesnt update if we ever change how ships are unlocked and is likely to be overlooked. It is 100% possible to do it nicely, it just isn't trivial.

**Comment by Pairjax** [comment]
Adding upper bound amount required: Rejected. Ginger has already added the feature for lower-bound, but it's a relatively large amount of work for the amount it gives back to the community.
Adding rep requirement: Considering. It depends on how we plan to redesign the plugins in the future. If it would be easy to add in the new system, we'll go ahead and add it.
