### ISSUE TITLE
Vertical engines don't move

### ISSUE THREAD

**Issue by BundtCake** [GingerWalnut/SQBeyondPublic#80]
They do however consume fuel and break blocks

**Comment by fiercedude** [comment]
The can mover vertically, but only when making a 1x1 hole. The power in a block gets directed the direction the furnace is facing, with the exception of the furnace the engine sign in placed on. Because furnaces can’t face up or down, they can’t send power to any drills above or below them. Because of this only 1x1 drills work vertically because of the sign being able to tell the power where to go. Imo this needs some solution.

**Comment by Seamonster778778778788** [comment]
is this still broken? @BundtCake @fiercedude

**Comment by Jarkyc** [comment]
Think this was fixed, and no reply.
